export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';

export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const CREATE_BOARD_SUCCESS = 'CREATE_BOARD_SUCCESS';
export const LOAD_BOARD_SUCCESS = 'LOAD_BOARD_SUCCESS';
